# Generated by Django 4.1 on 2022-08-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211111_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.book')),
                ('reader_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reader Name')),
            ],
        ),
    ]
